---
- name: ceph-dash - run service
  docker_service:
    project_name: ceph_dash
    definition:
      version: '2'
      services:
        ceph_dash:
          restart: unless-stopped
          image: "{{ ceph_dash_image }}"
          environment:
            CEPHMONS: "{{ ceph_dash_mons|join(',') }}"
            KEYRING: "{{ ceph_dash_keyring }}"
            NAME: "{{ ceph_dash_keyring_name }}"
          ports:
            - "{{ ceph_dash_host }}:{{ ceph_dash_port }}:5000"
          volumes:
            - "/etc/hosts:/etc/hosts:ro"
