---
- name: Install required packages
  package:
    name: bash-completion
    state: present
  become: true

- name: adminer - include tasks
  include: adminer.yml
  tags: adminer
  when:
    - configure_adminer|bool
    - adminer_groupname in group_names

- name: phpmyadmin - include tasks
  include: phpmyadmin.yml
  tags: phpmyadmin
  when:
    - configure_phpmyadmin|bool
    - phpmyadmin_groupname in group_names

- name: rally - include tasks
  include: rally.yml
  tags: rally
  when:
    - configure_rally|bool
    - rally_groupname in group_names

- name: sshconfig - include tasks
  include: sshconfig.yml
  tags: sshconfig
  when:
    - configure_sshconfig|bool
    - sshconfig_groupname in group_names
