---
- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ required_packages_helper }}"

- name: cephclient - include tasks
  include: cephclient.yml
  tags: cephclient
  when: configure_cephclient|bool

- name: phpmyadmin - include tasks
  include: phpmyadmin.yml
  tags: phpmyadmin
  when: configure_phpmyadmin|bool

- name: openstackclient - include tasks
  include: openstackclient.yml
  tags: openstackclient
  when: configure_openstackclient|bool

- name: rally - include tasks
  include: rally.yml
  tags: rally
  when: configure_rally|bool

- name: sshconfig - include tasks
  include: sshconfig.yml
  tags: sshconfig

- name: wrapper - include tasks
  include: wrapper.yml
  tags: wrapper
