# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ required_packages_helper }}"

- name: Include phpmyadmin tasks
  include: phpmyadmin.yml
  tags: phpmyadmin
  when: configure_phpmyadmin|bool
