---
- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0750
  become: true
  with_items:
    - "{{ openstackclient_directory }}"

- name: Run service openstackclient
  docker_service:
    project_name: openstackclient
    definition:
      version: '2'
      services:
        openstackclient:
          restart: unless-stopped
          image: "{{ openstackclient_image }}"
          entrypoint: sleep infinity
          volumes:
            - "{{ openstackclient_directory }}:/configuration:ro"
            - "/etc/hosts:/etc/hosts:ro"
