---
- name: openstackclient - create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0750
  become: true
  with_items:
    - "{{ openstackclient_configuration_directory }}"
    - "{{ openstackclient_data_directory }}"
    - "{{ openstackclient_docker_compose_directory }}"

- name: openstackclient - copy docker-compose.yml file
  template:
    src: openstackclient/docker-compose.yml.j2
    dest: "{{ openstackclient_docker_compose_directory }}/docker-compose.yml"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640

- name: openstackclient - pull images
  command: "docker-compose -f {{ openstackclient_docker_compose_directory }}/docker-compose.yml pull"
  register: result
  changed_when: ('Downloaded' in result.stdout)

- name: openstackclient - run service
  command: "docker-compose -f {{ openstackclient_docker_compose_directory }}/docker-compose.yml up -d --remove-orphans --no-build"
  register: result
  changed_when: ('Creating' in result.stdout or 'Recreating' in result.stdout)

- name: openstackclient - copy wrapper scripts
  template:
    src: "wrapper/{{ item }}.j2"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
  with_items:
    - openstack
    - ospurge
  become: true
