---
- name: Copy wrapper scripts
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
  with_items:
    - src: wrapper/ceph.j2
      dest: "/usr/local/bin/ceph"
    - src: wrapper/openstack.j2
      dest: "/usr/local/bin/openstack"
