---
- name: wrapper - copy scripts
  template:
    src: "wrapper/{{ item }}.j2"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
  with_items:
    - ceph
    - openstack
    - rally
    - rbd
