---
- name: Install python2
  hosts: all
  gather_facts: no

  tasks:
  - name: Install python2
    raw: test -e /usr/bin/python || (test -e /usr/bin/apt && (apt -y update && apt install -y python-minimal))
    register: result
    changed_when: result.rc != 0
    become: true

- name: Playbook for preparations
  hosts: all

  vars:
    docker_user: ubuntu

  roles:
  - role: osism.docker

- name: Playbook for role testing
  hosts: all
  connection: paramiko

  vars:
    configure_ceph_dash: yes
    configure_cephclient: yes
    configure_openstackclient: yes
    configure_phpmyadmin: yes
    configure_rally: yes
    configure_sshconfig: yes
    operator_user: ubuntu
    operator_group: ubuntu

  roles:
  - role: ../../ansible-helper
